global:
  error-sound: "ENTITY.VILLAGER.NO"

spawn:
  teleport-delay-seconds: 5
  cooldown-seconds: 10
  teleporting-sound: "BLOCK.NOTE_BLOCK.PLING"
  default-spawn: "1"

invsee:
  title: "&fInvSee: &#38c1fc%target%"

broadcast:
  sound: "BLOCK.NOTE_BLOCK.BELL"

discord:
  sound: "BLOCK.NOTE_BLOCK.PLING"
  lines:
    -  "&#38c1fcᴊᴏɪɴ ᴛʜᴇ Example ᴄᴏᴍᴍᴜɴɪᴛʏ"
    -  "&#38c1fc&l•&r &f&ndiscord.gg/yourserver"

live:
  cooldown-minutes: 15
  sound: "BLOCK.NOTE_BLOCK.BELL"
  lines:
    - ""
    - "  &#38c1fc&l%player% is now live!"
    - ""
    - "  &7Watch the stream:"
    - "  &f%link%"
    - ""

death:
  # Leave empty to disable
  prefix: "&#ff0000☠ "
  message-color: "&#ff0000"
  suffix: "&#ff0000."

media:
  title: "&7ᴍᴇᴅɪᴀ ʀᴀɴᴋ"
  filler:
    enabled: false
    material: "GRAY_STAINED_GLASS_PANE"
    name: " "
    lore: []
  item:
    material: "LEATHER_HELMET"
    name: "&#f73f9b📽ᴍᴇᴅɪᴀ ʀᴀɴᴋ"
    lore:
      - ""
      - "&#f73f9bRequirements: (only one needed)"
      - "&#f73f9b-&f 25 average viewers on a Stream"
      - "&#f73f9b-&f 100 average viewers on a TikTok Stream"
      - "&#f73f9b-&f 5k Views on a Youtube Video"
      - "&#f73f9b-&f 50k Views on a TikTok"
      - "&#f73f9b-&f 50k Views on a Youtube Short"
      - "&#f73f9b-&f 50k Views on a Instagram Reel"
      - ""
      - ""
      - "&#f73f9bReminders:"
      - "&8-&7 Must have IP on screen"
      - "&8-&7 Must be from the new season"
      - "&8-&7 Create ticket in discord for the rank"
      - "&8-&7 It lasts 90 days and has all top rank perks"
    leather-color: "#91255b"
    command: "discord"
    runAsConsole: false

moderation:

  chat-cooldown:
    enabled: true
    cooldown-millis: 2000
    bypass-permission: "servercore.moderation.bypass.cooldown"

  similarity:
    enabled: true
    threshold: 0.85
    max-compare-length: 100
    time-window-millis: 30000
    bypass-permission: "servercore.moderation.bypass.similarity"

  uppercase:
    enabled: true
    max-uppercase-percent: 70
    min-letters-to-check: 8
    bypass-permission: "servercore.moderation.bypass.uppercase"

  blacklist:
    enabled: true
    match-mode: "WHOLE_WORD" # WHOLE_WORD or CONTAINS (not recommended)
    ignore-case: true
    bypass-permission: "servercore.moderation.bypass.blacklist"
    words:
      - "nigga"
      - "nigger"
      - "retard"
      - "bastard"
      - "faggot"
  command-cooldown:
    bypass-permission: "servercore.moderation.bypass.command"
    global:
      enabled: true
      cooldown-millis: 1000
    per-command:
      example: 2000